name: clima_clean_bloc_tdd
description: "Weather app with clean architecture, BLoC and TDD"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  http: ^1.2.1
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true